### ISSUE TITLE
Can't unserialize

### ISSUE THREAD

**Issue by Luke-SF** [kvz/locutus#109]
When I try to unserialize this, for example:
http://api.wordpress.org/plugins/info/1.0/nextgen-gallery

I get an error:
unserialize(document.documentElement.textContent)
SyntaxError: Unknown / Unhandled data type(s): o

**Comment by kvz** [comment]
Thanks for reporting, and sorry for the long wait. This project and my motivation were in a bad spot. I recently did a lot of work to breathe new life into it (http://locutus.io/2016/05/announcing-locutus/).

It seems our unserialize function needs some love. @kukawski I noticed you self-assigned this one in  #190, did you have plans to attack it? Refs #257

**Comment by kukawski** [comment]
Partial support for the "O" type was just merged to master. I was able to unserialize the nextgen-gallery string. Closing the ticket.

**Comment by kvz** [comment]
🙏💥
