### ISSUE TITLE
Question on how to use the pack() written in js

### ISSUE THREAD

**Issue by ttback** [kvz/locutus#114]
I have an old php snippet for hex to binary conversion
$data = pack("H" . strlen($hexstr), $hexstr);
But I am unable to refactor this using your js pack() library. Could you share some tip on how to migrate the pack() from php to js

**Comment by kvz** [comment]
Thanks for reporting, and sorry for the long wait. This project and my motivation were in a bad spot. I recently did a lot of work to breathe new life into it (http://locutus.io/2016/05/announcing-locutus/). As part of this I'm going over all issues and PRs now. More information was requested here by @Reggino but none was provided, so I'm closing this for now. Feel free to re-open with more info.
