### ISSUE TITLE
pack() function bug

### ISSUE THREAD

**Issue by enginer** [kvz/locutus#123]
Native php:
$str = 'd527592b83555a6a50692b384c9f1906a3b56b49';
$p_str = pack('H*',$str); // hex view: D5 27 59 2B  83 55 5A 6A  50 69 2B 38  4C 9F 19 06  A3 B5 6B 49

phpJS:
var $str = 'd527592b83555a6a50692b384c9f1906a3b56b49';
var $p_str = pack('H*',$str);  // hex view: C3 95 27 59  2B C2 83 55  5A 6A 50 69  2B 38 4C C2  9F 19 06 C2  A3 C2 B5 6B  49

**Comment by kvz** [comment]
Thanks for reporting, and sorry for the long wait. This project and my motivation were in a bad spot. I recently did a lot of work to breathe new life into it (http://locutus.io/2016/05/announcing-locutus/). As part of this I'm going over all issues and PRs now. More information was requested here by @Reggino but none was provided, so I'm closing this for now. Feel free to re-open with more info.
