### ISSUE TITLE
sprintf issue with %g

### ISSUE THREAD

**Issue by ray007** [kvz/locutus#174]
It seems that
```sprintf("%3g", 1020.9999999999999)``` results in `"1020.9999999999999"` instead of `"1021"`.

**Comment by kvz** [comment]
Thanks for reporting, and sorry for the long wait. This project and my motivation were in a bad spot. I recently did a lot of work to breathe new life into it (http://locutus.io/2016/05/announcing-locutus/). We'll take a look at you PR and discuss further there.
