### ISSUE TITLE
serialize close object width ; and at php not close

### ISSUE THREAD

**Issue by vacho** [kvz/locutus#180]

**Comment by a-sav** [comment]
Variable 'type' leaked to global namespace and changed by recursive function calls, causing this bug.

phpjs/functions/var/serialize.js

Change line 68 from:
`type = _getType(mixed_value);`
to:
`var type = _getType(mixed_value);`

**Comment by kvz** [comment]
Thanks for reporting, and sorry for the long wait. This project and my motivation were in a bad spot. I recently did a lot of work to breathe new life into it (http://locutus.io/2016/05/announcing-locutus/). In this push I also fixed the problem you reported. Closing this one.
