### ISSUE TITLE
Include synch

### ISSUE THREAD

**Issue by vaso123** [kvz/locutus#185]
Hi!

I need the include function for my project, so i just copied it from your site, and insert it into my functions.php

It works, but not as i expected.

some code (i just write the logic):

app.js:

var a = 1;
include('test.js');
console.log('After include: ' + a);

test.js:
a = 2;
console.log('After adding one: ' + a);

So, what i expecting on the console is:
After adding one: 2
After include: 2

But the result is:
After include: 1
After adding one: 2

**Comment by kvz** [comment]
Thanks for reporting, and sorry for the long wait. This project and my motivation were in a bad spot. I recently did a lot of work to breathe new life into it (http://locutus.io/2016/05/announcing-locutus/). Unfortunately for your issue this also means it will fall a bit out of scope, as we're not aiming to port entire languages anymore, but just standard libraries.
