### ISSUE TITLE
Fork me on Github

### ISSUE THREAD

**Issue by rands0n** [kvz/locutus#188]
The image does not appear right because the body of the document is with a `position: relative;`.

![phpjs](https://cloud.githubusercontent.com/assets/4191734/4278325/f7250798-3d16-11e4-8b54-58896627783f.PNG)

Removing the `position: relative;` is ok. What you think?

![phpjs-right](https://cloud.githubusercontent.com/assets/4191734/4278348/2d57f88e-3d17-11e4-8fe8-76fbb59a20c5.PNG)

**Comment by kvz** [comment]
This issue is deprecated due to the move to Locutus http://locutus.io/2016/05/announcing-locutus/
