### ISSUE TITLE
array_column support

### ISSUE THREAD

**Issue by yangweijie** [kvz/locutus#192]
We do not have a replace of 'array_column' Came out after php5.4.Hope you consider to realize an amazing one！！

**Comment by tristanleboss** [comment]
Here is the PHP code for the recommended userland implementation for PHP lower than 5.5:

https://github.com/ramsey/array_column/blob/master/src/array_column.php

It just need to be ported to PHP.js but should be possible.

**Comment by kvz** [comment]
I either of you have a rainy Sunday afternoon to spare, Locutus is welcoming PRs again! Will close this in the meantime.
