### ISSUE TITLE
money_format wrongly formatting floats

### ISSUE THREAD

**Issue by evgenius** [kvz/locutus#213]
For en_US.utf8 `money_format('%n', 1003.998);` returns `$1,003.100`

**Comment by theaqua** [comment]
Try [accounting.js](http://josscrowcroft.github.io/accounting.js/).

**Comment by evgenius** [comment]
@theaqua Thank you. Looks like I have the patch but didn't create a PR. Need to check it.

**Comment by kvz** [comment]
Thanks for reporting, and sorry for the long wait. This project and my motivation were in a bad spot. I recently did a lot of work to breathe new life into it (http://locutus.io/2016/05/announcing-locutus/) and am happy to take a look at your issue. We'll check out the PR and close this issue to keep the discussion in a central place.
