### ISSUE TITLE
Error in AngularJS

### ISSUE THREAD

**Issue by bobvanluijt** [kvz/locutus#215]
Hi there,

Great extension, I would like to use this one in AngularJS but I'm getting this error:

TypeError: undefined is not a function
    at strip_tags (001.js:8)
    at 001.js:102
    at angular.js:13175
    at l.$get.l.$eval (angular.js:14388)
    at l.$get.l.$digest (angular.js:14204)
    at l.$get.l.$apply (angular.js:14493)
    at l (angular.js:9650)
    at O (angular.js:9840)
    at XMLHttpRequest.w.onload (angular.js:9781)

Line 8 in this case is:
return input.replace(commentsAndPhpTags, '').replace(tags, function($0, $1) { }

**Comment by kvz** [comment]
Thanks for reporting, and sorry for the long wait. This project and my motivation were in a bad spot. I recently did a lot of work to breathe new life into it (http://locutus.io/2016/05/announcing-locutus/) and am happy to take a look at your issue.

Is this still happening? Might you have some code so we can reproduce more easily?

**Comment by bobvanluijt** [comment]
Hi man, no problem, I guess I solved it 😁

Thanks for getting back though, congrats on Locutus!

**Comment by kvz** [comment]
Thanks!
