### ISSUE TITLE
Browser tests do not work

### ISSUE THREAD

**Issue by plepe** [kvz/locutus#229]
Is there some guidance how to get browser tests to work? I already fixed startup (see #228) as the paths were wrong and there was some deprecation warning, but the file that does finally load, contains some very old version of the strtotime function (and only the strtotime function). How to re-create the `test/browser/index.html` with new functions?

**Comment by kvz** [comment]
I'm not sure if this ever worked to be honest. I believe it was left in a prototyping state to be finished later - but never saw a need for it when the cli version was ported from rhino (yeah..) to node.

**Comment by plepe** [comment]
That's what I thought :-) Would be good to have them though, as you can't catch browser differences/incompatibilities with nodejs ;)

**Comment by kvz** [comment]
Would be nice indeed - although tbh I'm not using php.js myself anymore so it's hard for me muster up the motivation / justify the time spent for doing this. Happy to be non-blocking here and facilitate/merge such initiatives though if you'd like to take a stab at it>

**Comment by plepe** [comment]
*cough* I think I'm also pretty busy with other projects ...

I suggest we just leave it open and see what happens :)

**Comment by generalredneck** [comment]
did someone mention writing tests? 

![tumbleweed](http://www.animecentral.net/gallery/albums/userpics/10001/normal_tumbleweed.gif)

**Comment by kvz** [comment]
Tests are there, just need to also be able to run them in browser vs just cli, feel free to take a stab :)

**Comment by kvz** [comment]
We are generating Mocha tests now (more info here http://locutus.io/2016/05/announcing-locutus/), and executing those on cli on Travis CI. Since it's mocha it might be easier to get it working in the browser as well. 

I'll be closing this issue for now though as it seems there isn't an interest big enough to put the effort into it at this point.
