### ISSUE TITLE
bcscale not preserved

### ISSUE THREAD

**Issue by rbro** [kvz/locutus#23]
I'm seeing an issue where the bcscale is not preserved when using the bcmath functions.  The following JS code should alert "0.33333", but it alerts "0" instead:

bcscale(5);
alert(bcdiv(1, 3));

It looks like it's occurring because each call to bcdiv calls this._phpjs_shared_bc() which returns a new libbcmath object each time.

This issue does not exist in the project https://sourceforge.net/projects/bcmath-js because libbcmath is a global object there.

Is there a way to preserve the bcscale() call with the way that php.js is including the libbcmath library?

**Comment by kvz** [comment]
Sorry for the long wait. This project and my motivation were in a bad spot. I recently did a lot of work to breathe new life into it (http://locutus.io/2016/05/announcing-locutus/). As part of this, npm is now the main distribution platform, and there's examples of how to use bcdiv right on http://locutus.io/php/bc/bcdiv/. Closing this : )
