### ISSUE TITLE
serialize and unserialize bug?

### ISSUE THREAD

**Issue by jimtang9527** [kvz/locutus#238]
array:
[ { hash: 'X12', device_id: 1, time: 1440057773801 },
  { hash: 'X11', device_id: 1, time: 1440057773688 } ]
php.serialize
a:2:{i:0;a:3:{s:4:"hash";s:3:"X12";s:9:"device_id";i:1;s:4:"time";i:1440057773801;};i:1;a:3:{s:4:"hash";s:3:"X11";s:9:"device_id";i:1;s:4:"time";i:1440057773688;};};
php.unserialize
it's not work

**Comment by kukawski** [comment]
I will work on it.

**Comment by kukawski** [comment]
@minicloud how did you get the serialized string? Neither our serialize implementation nor the php serialize function returns string formatted this way. Also PHP's unserialize can't handle this string. To me this issue seems to be invalid.

**Comment by kvz** [comment]
Closing as no more information was provided
