### ISSUE TITLE
json_encode error

### ISSUE THREAD

**Issue by JohnnieFucker** [kvz/locutus#244]
there's a error when I use phpjs json_encode in my project
I found it,s undefined of  this.window.JSON,  
is there anything wrong with dependencies?

Unexpected error type in json_encode()
at Object.exports.json_encode (/data/www/htdocs/tsb-api/node_modules/phpjs/build/npm.js:3842:15)

**Comment by kvz** [comment]
Might you have the steps to reproduce for us?
