### ISSUE TITLE
strtotime() returns dates from 2001 instead of this year when passing only month and day

### ISSUE THREAD

**Issue by chrisblakley** [kvz/locutus#261]
I happened to notice this when playing around with the function. For what I'm using it for this is not an problem, but I thought it was worth noting.

When passing a date like "november 20" the UTC time returned is ```1006232400``` (which is November 20, 2001). The PHP version defaults to the current year, which would return ```1447995600``` for November 20, 2015.

I looked through the documentation to see if this was a known part of the function, but didn't see anything specific regarding that, so I apologize if this has been addressed before.

**Comment by kukawski** [comment]
I'm getting `false` when calling `strtotime('november 20')`, this means that the phpjs implementation doesn't recognize this format. This function needs a lot more work to recognize all formats supported by PHP (I'm working on it), but clearly it doesn't return timestamp mentioned by you.

**Comment by chrisblakley** [comment]
I read through some more of the documentation and I didn't think about cross-browser being an issue. I tested again in Firefox and Safari which returned ```false``` just as you described. The issue of returning ```1006232400``` appears to be isolated to Chrome.

As I said, I just wanted to note it as it appears to be a minor issue- the function is still very impressive regardless.

**Comment by kvz** [comment]
Closing this for now as @kukawski is working on a big rewrite as mentioned in #273
