### ISSUE TITLE
strtotime: Fails with timestamp origin

### ISSUE THREAD

**Issue by LudovicGuillaume** [kvz/locutus#267]
1.

`strtotime('+1 years', strtotime('1969-01-01 01:00:00'))`

returns `false` instead of `0`.

**Fix :** replace `if (!process(match[i])) {` by `if (isNaN(process(match[i]))) {`

2.

`new Date(strtotime('+1 years', 0) * 1000)`

returns current date instead of `1971-01-01 **:**:**`.

*Workaround :* `new Date(strtotime('+1 years', '0') * 1000)`

**Fix :** replace `date = now ? new Date(now * 1000) : new Date();`
by `date = !isNaN(now) ? new Date(now * 1000) : new Date();`
or if you want to keep string input `date = now !== undefined ? new Date(now * 1000) : new Date();`
or `date = now !== undefined && now !== null ? new Date(now * 1000) : new Date();`

Note: I'm GMT+1.
Note²: I used `years` but it should be possible to use something else.

**Comment by kvz** [comment]
Thanks for reporting! I'm cleaning out the issues a little bit and will be closing this for now as @kukawski is working on a big rewrite as mentioned in #273 #261
