### ISSUE TITLE
strnatcasecmp returns incorrect values

### ISSUE THREAD

**Issue by denaje** [kvz/locutus#268]
`strnatcasecmp('0A', '5N')` incorrectly returns `1`. PHP 5.6.16 and PHP 7 correctly return `-1`.

**Comment by kukawski** [comment]
This issue is fixed now.

**Comment by seanthebean** [comment]
Thanks so much @kukawski ! Would you mind also posting here when the fix is released?

**Comment by kvz** [comment]
Hey there, I just pushed out [v2.0.5](https://github.com/kvz/locutus/blob/master/CHANGELOG.md#v205) which contains this work.
