### ISSUE TITLE
String truncation in JavaScript (substring)

### ISSUE THREAD

**Issue by shorifali** [kvz/locutus#269]
I have one approach regarding truncation of string:

```javascript

var stringVar = 'Lorem Ipsum';
var truncatedString = stringVar.truncate( startPosition, endPosition[, tailString]);

```

Argument description:

`startPosition`: Indicates the start position of truncation (it checks the length of the string for overflow).
Type: Integer

`endPosition`: Indicates the last position of truncation (it checks the length of the string for overflow).
Type: Integer

`tailString`:  Optional. Indicates a tail string (or html) to be added after truncation.
Type: String

Return type: Returns string and sometimes html based on `tailString`

Though it is not in PHP, but still it could be a good thing to use.

Thanks,
Shorif

**Comment by kvz** [comment]
Thanks for the input! This project strictly limits itself to porting standard libraries of other languages though, so I'll have to close this one, sorry about that!
