### ISSUE TITLE
Better implementation for array_rand

### ISSUE THREAD

**Issue by renzhn** [kvz/locutus#288]
The implementation on [http://phpjs.org/functions/array_rand/](http://phpjs.org/functions/array_rand/) is bad, if the `input` arrary is large (say 1000000), and `num_req` is large (say 1000000), it will hang as when picking the last item, it will end only if pick the unpicked one by RANDOM, which is 1/1000000 possibility.

**Comment by kukawski** [comment]
I'm on it

**Comment by kvz** [comment]
Closing this as the discussion can continue in #289
