### ISSUE TITLE
npm WARN deprecated while installing phpjs

### ISSUE THREAD

**Issue by digitaldonkey** [kvz/locutus#294]
### Description

Installing npm dependencies it seems that phpjs 1.3.2 uses some very outdated packaged, causing warnings:

```
npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. 

npm ls graceful-fs

[...]
└─┬ kss@3.0.0-beta.14
  └─┬ twig@0.9.5
    └─┬ phpjs@1.3.2
      ├─┬ glob@3.2.1
      │ └── graceful-fs@1.2.3
      └─┬ mocha@1.17.0
        └─┬ glob@3.2.3
          └── graceful-fs@2.0.3

npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade

npm ls jade
[...]
└─┬ kss@3.0.0-beta.14
  └─┬ twig@0.9.5
    └─┬ phpjs@1.3.2
      └─┬ mocha@1.17.0
        └── jade@0.26.3

```
There are updates available:

https://github.com/isaacs/node-glob/tree/v7.0.3
https://github.com/mochajs/mocha/tree/v2.5.3

**Comment by digitaldonkey** [comment]
Submitted Issue in phpjs
[npm WARN deprecated while installing phpjs](https://github.com/kvz/locutus/issues/294) (https://github.com/kvz/locutus/issues/294)

**Comment by kvz** [comment]
Hi, have you considered upgrading to Locutus?

**Comment by digitaldonkey** [comment]
Actually I have no clue. Just want my theme to get installed without warnings. 
phpjs is part of kss-node. https://github.com/kss-node/kss-node/issues/326

**Comment by JohnAlbin** [comment]
omg. The 1.3.2 version of phpjs on npm is deeply flawed.

```json
  "dependencies": {
    "cli": "0.4.4-2",
    "deep-equal": "0.1.2",
    "glob": "3.2.1",
    "js-beautify": "1.4.2",
    "mocha": "1.17.0",
    "send": "0.1.0",
    "underscore": "1.5.2"
  },
```

No node.js library should ever have mocha as a dependency; it is a test runner that should be a dev dependency. It looks like the git repository for phpjs library has been replaced with this one (locutus), but does not contain any of the original code. (locutus 1.3.2 !== phpjs 1.3.2.) So it's impossible to even fix the problem.

**Comment by JohnAlbin** [comment]
This issue can be closed. Twig.js will switch to locutus since it is just using a couple of the files.

**Comment by kvz** [comment]
@JohnAlbin Thanks. Good thing that you are switching to Locutus, devDependencies were hardly the only thing flawed with php.js. If you really want to know, there's more background here http://locutus.io/2016/05/announcing-locutus/
