### ISSUE TITLE
some functions are not there.

### ISSUE THREAD

**Issue by Shereen92** [kvz/locutus#295]
- [ ] Have you checked the guidelines in our [Contributing](https://github.com/kvz/locutus/blob/master/CONTRIBUTING.md) document?

### Description

I'm using the phpjs library for my javascript project, which I'm running in a virtual box, but whenever I call some functions (e.g. session_start()) that should supposedly be part of the phpjs library I get the following runtime error:
**Object (phpjs) has no method 'session_start'.** 

session_start() is not under the experimental section, so it should be there. Any clue on where the problem could be?

Cheers,
Shereen

**Comment by kvz** [comment]
Hi @Shereen92, if you rely on this you should pin the 1.3.2 version of this project. I invite you to read http://locutus.io/2016/05/announcing-locutus/ for more background information.

**Comment by Shereen92** [comment]
Oh Thank you so much. Wiill check it out.
