### ISSUE TITLE
Some functions are missing- php

### ISSUE THREAD

**Issue by Shereen92** [kvz/locutus#298]
After switching from phpjs, I'm using locutus/php and it is very useful. Great work!
I noticed that some functions are missing such as those for session, mysql and others.
I wonder when you will be adding support for those.

Cheers,
Sherin

**Comment by kvz** [comment]
Hi @Shereen92, those functions relied on hacks and global state quite a bit, and have been deprecated. I have no intention of adding them back to Locutus unfortunately. If you want to continue to use them you'll have to rely on the 1.3.2 version. More information in http://locutus.io/2016/05/announcing-locutus/.

**Comment by Shereen92** [comment]
I tried to switch to version 1.3.2 but got the following error:
npm ERR! Error: version not found: 1.3.2 : locutus/1.3.2

so I figured you mean: phpjs@1.3.2. However, these functions are also missing there!

**Comment by kvz** [comment]
Ah, I initially thought you were talking about a regression. In this case I'm sorry to report we never had those functions in the first place then.
