### ISSUE TITLE
PHP "strtotime()" method is missing "yesterday"

### ISSUE THREAD

**Issue by Coriou** [kvz/locutus#302]
I've been working with Locutus' port of PHP's strtotime() which works like a charm, except for the keyword "yesterday".

Ex : 

`console.log( strtotime( 'yesterday', Math.floor(new Date() / 1000) ) ); // false`
`console.log( strtotime( '1 day ago', Math.floor(new Date() / 1000) ) ); // correct timestamp`

**Comment by kukawski** [comment]
`Yesterday` is currently not supported. I'm working on strtotime and I'm basically writing the implementation from scratch. New implementation will support vast majority of the formats handled by PHP. Can't promise, when the new code will be ready, as I have many other tasks on my head :-/

**Comment by Coriou** [comment]
> Yesterday is currently not supported. I'm working on strtotime and I'm basically writing the implementation from scratch. New implementation will support vast majority of the formats handled by PHP. Can't promise, when the new code will be ready, as I have many other tasks on my head :-/

Hey, well thanks a lot for working on it and obviously no pressure at all, take your time ! In my case, I've made the adjustments in my own code so it's not even a "breaking bug" :)

**Comment by kukawski** [comment]
yesterday support is added in this pull request. Should be released soon: https://github.com/kvz/locutus/pull/373
