### ISSUE TITLE
round(4096.485, 2) => 4096.48

### ISSUE THREAD

**Issue by morskoyzmey** [kvz/locutus#306]
It's a magic border.
Although some bigger numbers works right too. For example 14096.485

**Comment by JoniJnm** [comment]
The problem:

```
> console.log(4096.485 * 100)
409648.49999999994
```

One solution could be to use epsilon in the comparison:

`isHalf = value % 1 === 0.5 * sgn`

http://stackoverflow.com/questions/5037839/avoiding-problems-with-javascripts-weird-decimal-calculations

**Comment by kukawski** [comment]
This is now fixed. It turned out that PHP performs an additional rounding to some specific precision before rounding to the precision the function caller expects. 
The aim is to deliver “human-understandable” results despite FP specifics/limitations. 
I’m closing the ticket.
