### ISSUE TITLE
Using locutus in Angular 2 Error

### ISSUE THREAD

**Issue by seanmavley** [kvz/locutus#315]
### Description
I'm attempting to use locutus in Angular 2.

I've installed the locutus typings (`$ npm install @types/locutus@0.0.2` and locutus (`npm install locutus` ) itself

As usual, I try to import in Angular 2 and use

```
import { Injectable } from '@angular/core';
import { php } from 'locutus';

export class HexhelperService {
  constructor(private php: php) { 
    // Error: Cannot find name 'php'
  }
}
```

the above throws the error: `Cannot find name 'php'`

```
import { Injectable } from '@angular/core';
import { php } from 'locutus';
export class HexhelperService {
  constructor(php) { 
    // Error: Can't resolve all parameters for HexhelperService: (?). at SyntaxError.BaseError [as constructor]
  }
}
```

What am I missing?

**Comment by kvz** [comment]
Not sure what's going on, but we do not support including all the php sources, as that means shipping several megabytes of mostly unused js to the end user.
