### ISSUE TITLE
similar_text is very slow

### ISSUE THREAD

**Issue by martis903** [kvz/locutus#321]
https://github.com/kvz/locutus/blob/master/src/php/strings/similar_text.js
works very slow. To compare less than 100 pair of strings (less than 20 chars each) it takes minutes.

**Comment by Theriault** [comment]
Could you provide example code? I'm able to do 84k comparisons a second (more than 20 chars each).

https://jsperf.com/similar-text/1

**Comment by martis903** [comment]
Thank you for the tests.
I used that function in Imacros javascript. It is clearly Imacros's fault.

2017-03-02 19:35 GMT+02:00 Theriault <notifications@github.com>:

**Comment by kukawski** [comment]
I will close the ticket based on above two comments. If the problem is still there, it can be reopened.
