### ISSUE TITLE
Unknown / Unhandled data types(s): u

### ISSUE THREAD

**Issue by JasonScopServ** [kvz/locutus#324]
Having an issue where unserialize() won't unserialize an object.

Error is: Unknown / Unhandled data types(s): u

**Comment by kukawski** [comment]
@JasonScopServ could you please add example string you tried to unserialize?

**Comment by cupliz** [comment]
i am facing the same problem, here is the string:

a:67:{s:9:"par_id";s:1:"0";s:8:"mod_id";s:2:"14";s:8:"cat";s:20:"toggle";s:4:"body";s:1679:"";s:4:"0_id";s:0:"";s:8:"0_coords";s:0:"";s:7:"0_parts";s:0:"";s:4:"1_id";s:0:"";s:8:"1_coords";s:0:"";s:7:"1_parts";s:0:"";s:4:"2_id";s:0:"";s:8:"2_coords";s:0:"";s:7:"2_parts";s:0:"";s:4:"3_id";s:0:"";s:8:"3_coords";s:0:"";s:7:"3_parts";s:0:"";s:4:"4_id";s:0:"";s:8:"4_coords";s:0:"";s:7:"4_parts";s:0:"";s:4:"5_id";s:0:"";s:8:"5_coords";s:0:"";s:7:"5_parts";s:0:"";s:4:"6_id";s:0:"";s:8:"6_coords";s:0:"";s:7:"6_parts";s:0:"";s:4:"7_id";s:0:"";s:8:"7_coords";s:0:"";s:7:"7_parts";s:0:"";s:4:"8_id";s:0:"";s:8:"8_coords";s:0:"";s:7:"8_parts";s:0:"";s:4:"9_id";s:0:"";s:8:"9_coords";s:0:"";s:7:"9_parts";s:0:"";s:5:"10_id";s:0:"";s:9:"10_coords";s:0:"";s:8:"10_parts";s:0:"";s:5:"11_id";s:0:"";s:9:"11_coords";s:0:"";s:8:"11_parts";s:0:"";s:5:"12_id";s:0:"";s:9:"12_coords";s:0:"";s:8:"12_parts";s:0:"";s:5:"13_id";s:0:"";s:9:"13_coords";s:0:"";s:8:"13_parts";s:0:"";s:5:"14_id";s:0:"";s:9:"14_coords";s:0:"";s:8:"14_parts";s:0:"";s:5:"15_id";s:0:"";s:9:"15_coords";s:0:"";s:8:"15_parts";s:0:"";s:5:"16_id";s:0:"";s:9:"16_coords";s:0:"";s:8:"16_parts";s:0:"";s:5:"17_id";s:0:"";s:9:"17_coords";s:0:"";s:8:"17_parts";s:0:"";s:5:"18_id";s:0:"";s:9:"18_coords";s:0:"";s:8:"18_parts";s:0:"";s:5:"19_id";s:0:"";s:9:"19_coords";s:0:"";s:8:"19_parts";s:0:"";s:5:"20_id";s:0:"";s:9:"20_coords";s:0:"";s:8:"20_parts";s:0:"";}

**Comment by cupliz** [comment]
i found that unserialize not working with non-encoded characters

**Comment by arokanto** [comment]
After stumbling on this myself, the most likely reason for that error is that you're trying unserialize `undefined`

**Comment by kukawski** [comment]
@arokanto thanks for the hint. I will check it and add code to handle this case.

**Comment by kukawski** [comment]
Fixed in latest master
