### ISSUE TITLE
Unknown / Unhandled data type(s): o

### ISSUE THREAD

**Issue by Drewsov** [kvz/locutus#325]
Try this from Wordpress 
O:8:"stdClass":3:{s:14:"trusted_header";s:11:"REMOTE_ADDR";s:8:"segments";i:1;s:7:"reverse";b:0;}

At least should be return stdClass... 
{"trusted_header":"REMOTE_ADDR","segments":1,"reverse":false}

**Comment by kukawski** [comment]
I will look into adding support for stdClass

**Comment by kukawski** [comment]
Just published a pull request that adds support for the "O" type for stdClass https://github.com/kvz/locutus/pull/403

**Comment by kukawski** [comment]
PR merged. Closing the ticket. Please feel free to re-open or file a new in case the function doesn't work for you.
