### ISSUE TITLE
PHP wordwrap differs slightly from the Locutus version

### ISSUE THREAD

**Issue by Loilo** [kvz/locutus#327]
If PHP's `wordwrap` inserts a break at a position where the next character is a whitespace, it absorbs that character, thus not starting the next line with a whitespace. The Locutus version currently does not mimick that behaviour.

For a PHP example, [see this codepad](http://codepad.org/NhkKy49E)

Note: In case there are multiple consecutive whitespace characters, only the first one is omitted.

I actually tried to fix that one myself but to be honest, the `wordwrap` function code is a pretty hot mess and I didn't have the confidence to touch it. :)

**Comment by kukawski** [comment]
I'll give it a try ;-)

**Comment by kukawski** [comment]
@Loilo I've added a pull request that should work for your case. I've also made the code more readable. Please review.
I will continue checking compatibility with PHP, because I found several other cases where the results slightly differ and will make a new patch for those.

**Comment by Loilo** [comment]
Readability is greatly improved and it gives same output as PHP for all quirky edge cases I've thrown at it.

According to [the one (!) jsperf case I created](https://jsperf.com/locutus-old-vs-new-wordwrap), both versions are roughly equally fast. Which version is faster differs from run to run. I ran the jsperf case in Chrome 58 and IE 11.

So far, I've got no objections against the changes.

**Comment by kvz** [comment]
Thanks for the thoroughness! I just merged https://github.com/kvz/locutus/pull/328
