### ISSUE TITLE
php/network/long2ip is missing the first & 0xFF

### ISSUE THREAD

**Issue by mkg20001** [kvz/locutus#343]
- [x] Have you checked the guidelines in our [Contributing](https://github.com/kvz/locutus/blob/master/CONTRIBUTING.md) document?

### Description

In src/php/network/long2ip.js the first " & 0xFF" is missing.

```
-  return [ip >>> 24, ip >>> 16 & 0xFF, ip >>> 8 & 0xFF, ip & 0xFF].join('.')
+  return [ip >>> 24 & 0xFF, ip >>> 16 & 0xFF, ip >>> 8 & 0xFF, ip & 0xFF].join('.')
```

**Comment by argosback** [comment]
@kvz this issue should be closed.

**Comment by kvz** [comment]
@argosback made you a collaborator so you can do this yourself from now on 😄
