### ISSUE TITLE
Support for php_strip_whitespace?

### ISSUE THREAD

**Issue by tomjn** [kvz/locutus#347]
- [x] Have you checked the guidelines in our [Contributing](https://github.com/kvz/locutus/blob/master/CONTRIBUTING.md) document?

### Description

Is `php_strip_whitespace` support intended? I see a lot of things were removed in the move from php.js to locutus, but I can't find any trace of it before or after.

[There is an implementation floating around that credits yourself and Brett Zamir](https://searchcode.com/codesearch/view/14389993/), but it produces similar but different output, making it useless for my purposes :(

**Comment by kvz** [comment]
Pre-locutus functions are saved in the https://github.com/kvz/locutus/tree/v1.3.2 tag for reference. That being said, we removed it for a good reason. That function locks the entire browser up and should only be used for experimentation and nothing else :)

**Comment by tomjn** [comment]
I can see that with the retrieval of remote stuff, though my local copy has that bit snipped out, I was hoping for the regex pattern part fixing as I'm dealing exclusively with strings.

Is there anything or anywhere you'd recommend I look next?

**Comment by kvz** [comment]
This comes with a whole bunch of disclaimers and recommendations against using, but since you seem to be knowing what you're doing: https://github.com/kvz/locutus/blob/v1.3.2/experimental/misc/php_strip_whitespace.js

**Comment by Knight-Yoshi** [comment]
Why not create a web worker to do this on a separate background thread, that way it doesn't lock up the browser?

**Comment by tomjn** [comment]
@Knight-Yoshi that could work, but in my case I already have the PHP string, I need to do the stripping in a way that matches the native PHP version, the two give differing output
