### ISSUE TITLE
sprintf formatting regression

### ISSUE THREAD

**Issue by ray007** [kvz/locutus#365]
- [x] Have you checked the guidelines in our [Contributing](https://github.com/kvz/locutus/blob/master/CONTRIBUTING.md) document?

### Description
After upgrading to the current version of `sprintf.js`, a formatter I'm using in my code does not work anymore.
The format string `%.*f` now results in `"f"` instead of a number with the precision taken from the argument list.

**Comment by kukawski** [comment]
In last patch I improved compatibility with PHP. The format you've used is not valid (per http://php.net/sprintf).
Previous sprintf implementation differed a lot from PHP's sprintf implementation.

Now a question to @kvz : what strategy should I follow? Keep backward compatibility with older locutus releases in mind or mimic PHP as close as possible?

**Comment by ray007** [comment]
Sounds like a bug in the php implementation to me. At least when looking at something like [https://en.wikipedia.org/wiki/Printf_format_string#Precision_field](https://en.wikipedia.org/wiki/Printf_format_string#Precision_field)

**Comment by kvz** [comment]
As a rule of thumb, I would mimic php's behavior as close as possible (while still being useful in/with pure js projects/objects), and not worry about backwards compatibility. We're not semver, and can bundle a *BREAKING* into the CHANGELOG.md for that function, in that PR.

--
Kevin van Zonneveld (kvz.io)
Co-founder at Transloadit (transloadit.com)
Core-author of tus (tus.io)

**Comment by ray007** [comment]
It's not just a breaking change, it's removing a feature.

**Comment by kukawski** [comment]
I'll look into restoring support for the dropped format. Maybe it turns out to be simple without breaking the PHP compatibility.

**Comment by kukawski** [comment]
It's now a tough nut to crack, because restoring the feature means breaking PHP compability.
If we can call it a PHP bug? Not sure, it's maybe on purpose, because PHP's sprintf is not just a wrapper around the C-function. [Here](https://github.com/php/php-src/blob/a7fe2570d3ce6915d4ea85c62c0f880ddc225ba7/ext/standard/formatted_print.c#L524) is the precision parsing, and [here](https://github.com/php/php-src/blob/a7fe2570d3ce6915d4ea85c62c0f880ddc225ba7/ext/standard/formatted_print.c#L206) applying the precision. I don't see any logic which is derived from `.*` format

**Comment by kukawski** [comment]
My plan is to port the C version of sprintf in the C-lang namespace of locutus. Hope this solution suits you.

**Comment by ray007** [comment]
Sounds good to me. Thank you.
When you do so, could you please trigger this thread here with another comment?

**Comment by kukawski** [comment]
@ray007 I've prepared a pull request (https://github.com/kvz/locutus/pull/368) implementing sprintf.
I tried to be as close as possible to the rules you've linked previously.
The implementation is not yet 100% complete, but I'll extend the function with new patches.
Please check if it works as expected for you.

**Comment by kukawski** [comment]
I will close the issue. In case there are problems with the new implementation, please raise new tickets.

**Comment by ray007** [comment]
Thanks.
I haven't yet updated since my target environment is ES5 only, will hopefully find time soon...
