### ISSUE TITLE
Bug in PHP parse_str function

### ISSUE THREAD

**Issue by JoniJnm** [kvz/locutus#366]
There is a bug in the function parse_str

```js
var data = {};
parse_str('a[][b]=1', data);
console.log(data);
```
The value of data is:

```js
{
    'a': {
        'b': 1
    }
}
```

But should be:

```js
{
    'a': [
        {
            'b': 1
        }
    ]
}
```

http://sandbox.onlinephpfunctions.com/code/5286b2e4c9f7aaced6bc5bfade41bf734ed0e315

**Comment by kukawski** [comment]
I've added a pull request with a fix for this issue https://github.com/kvz/locutus/pull/369

**Comment by kvz** [comment]
Thanks for fixing @kukawski!
