### ISSUE TITLE
"Notporting" Functions

### ISSUE THREAD

**Issue by ylluminate** [kvz/locutus#37]
With the advent of Node, it seems that many of the "Notporting" functions should now begin implementation.  Thoughts?

**Comment by kvz** [comment]
Thanks for reporting, and sorry for the long wait. This project and my motivation were in a bad spot. I recently did a lot of work to breathe new life into it (http://locutus.io/2016/05/announcing-locutus/). 

> But if it where up to me, all things echo default to console.log, all things file default to the fs module. And only if we detect those are not available to we do a stab at browser compatibility.

This bit made it into Locutus.

> But in having it in serverland would allow you to run .php scripts on v8. Which is also terrible, but in a fun way 👯

This goal didn't : )

But the good thing is Node is the primary target platform, with Browserify (and similar) as the recommended way to then target browsers.
