### ISSUE TITLE
locutus/php/url/urlencode not converting '~' to '%7E'

### ISSUE THREAD

**Issue by tpirc3** [kvz/locutus#371]
- [x] Have you checked the guidelines in our [Contributing](https://github.com/kvz/locutus/blob/master/CONTRIBUTING.md) document?

### Description

PHP's urlencode will convert '~' into '%7E'
`urlencode('~') ===  '%7E'`

locutus/php/url/urlencode doesn't convert '~'
`require('locutus/php/url/urlencode')('~') === '~'`

Since `encodeURIComponent` not converting '~',  may need to add `.replace(/~/g, '%7E')` in [locutus/php/url/urlencode's implementation](http://locutus.io/php/url/urlencode/).

**Comment by divinity76** [comment]
seems like the obvious course of action, try making a PR :)

**Comment by divinity76** [comment]
notably ***raw***urlencode keeps  ~ intact, urlenode() does not.
