### ISSUE TITLE
hex2bin function on locutus.io is `undefined`

### ISSUE THREAD

**Issue by divinity76** [kvz/locutus#376]
- [nope] Have you checked the guidelines in our [Contributing](https://github.com/kvz/locutus/blob/master/CONTRIBUTING.md) document?

### Description

on http://locutus.io/php/strings/hex2bin/ , the javascript code is just shown as `undefined`. 
screenshot: 
![image](https://user-images.githubusercontent.com/1874996/44981423-c6213e00-af72-11e8-9252-587e75d1511e.png)

**Comment by kukawski** [comment]
Thanks for reporting this. I will debug as soon as possible. It probably happened after my PR with build scripts changes.

**Comment by kvz** [comment]
Took a while because deploys were broken and I was too busy to look into it, but the patch is live now. Thanks for reporting and bearing with me! 💯
