### ISSUE TITLE
echo() - TypeError: stringToDOM(...).cloneNode is not a function

### ISSUE THREAD

**Issue by ghost** [kvz/locutus#64]
Happens when trying to `echo("<br>");` or any html code.
It also pops when you attempt to use `var_dump("<pre>");` or anything else that uses echo function for printing out the results on a screen, and the printed value contains DOM element.

From Firebug:
```
TypeError: stringToDOM(...).cloneNode is not a function
..._xhtml, 'div').cloneNode(true); // We will not actually append the div tag (just...
```

**Comment by kvz** [comment]
With the transition to Locutus, I have deprecated the XUL & XHTML writing straight to the dom. I'm sorry to have been stubborn in this one. For more information see http://locutus.io/2016/05/announcing-locutus/ and http://locutus.io/php/strings/echo/
